version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=iac_typescript
    ports:
      - 5432:5432
  api_test:
    build:
      dockerfile: Dockerfile.test
      context: ./api
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    environment:
      - DB_USER=docker
      - DB_PASS=docker
      - DB_HOST=postgres
      - DB_NAME=iac_typescript
    depends_on:
      - postgres
