# This is a basic workflow to help you get started with Actions

name: build, push and deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker:19.03.5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test
        run: |
          apk add python3
          pip3 install awscli
          docker build --compress -t $ECR_REPO:$GITHUB_SHA ./api
          $(aws ecr get-login --no-include-email --region us-east-1)
          docker push $ECR_REPO:$GITHUB_SHA
          docker tag $ECR_REPO:$GITHUB_SHA $ECR_REPO:latest
          docker push $ECR_REPO:latest

  terraform_plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: hashicorp/terraform:0.12.21

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test
        run: |
          cd deploy/,
          export TF_VAR_ecr_image_api=$ECR_REPO:$GITHUB_SHA,
          terraform init,
          terraform workspace select staging,
          terraform apply -auto-approve

  terraform_apply:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: hashicorp/terraform:0.12.21

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test
        run: |
          cd deploy/
          export TF_VAR_ecr_image_api=$ECR_REPO:$GITHUB_SHA
          terraform init
          terraform workspace select staging || terraform workspace new staging
          terraform plan
