name: build, push and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    container: docker:19.03.5
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: build_and_push
        run: |
          apk add python3
          pip3 install awscli
          docker build --compress -t ${{ secrets.ECR_REPO }}:$GITHUB_SHA ./api
          $(aws ecr get-login --no-include-email --region us-east-1)
          docker push ${{ secrets.ECR_REPO }}:$GITHUB_SHA
          docker tag ${{ secrets.ECR_REPO }}:$GITHUB_SHA ${{ secrets.ECR_REPO }}:latest
          docker push ${{ secrets.ECR_REPO }}:latest

  # terraform_plan:
  #   runs-on: ubuntu-latest
  #   container: hashicorp/terraform:0.12.21
  #   needs: [build_and_push]
  #   env:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
  #     TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: terraform_plan
  #       run: |
  #         echo "Running Terraform_plan..."
  #         export TF_VAR_ecr_image_api=${{ secrets.ECR_REPO }}:$GITHUB_SHA
  #         cd deploy/
  #         terraform init
  #         terraform workspace select staging || terraform workspace new staging
  #         terraform plan

  # terraform_apply:
  #   runs-on: ubuntu-latest
  #   container: hashicorp/terraform:0.12.21
  #   needs: [build_and_push, terraform_plan]
  #   env:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
  #     TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: terraform_apply
  #       run: |
  #         echo "Running Terraform apply..."
  #         export TF_VAR_ecr_image_api=${{ secrets.ECR_REPO }}:$GITHUB_SHA
  #         cd deploy/
  #         terraform init
  #         terraform workspace select staging
  #         terraform apply -auto-approve

  cdktf_deploy:
    runs-on: ubuntu-latest
    container: node:15.7.0-alpine
    needs: [build_and_push]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
    steps:
      - uses: actions/checkout@v2
      - name: cdktf_deploy
        run: |
          echo "Running cdktf deploy..."
          export TF_VAR_ecr_image_api=${{ secrets.ECR_REPO }}:$GITHUB_SHA
          cd infra/
          npm i
          npm run build
          npm run deploy:ci
