# This is a basic workflow to help you get started with Actions

name: validate and test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate_terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: validate terraform
        run: |
          echo "Validate Terraform",
          cd deploy/,
          terraform init -backend=false,
          terraform validate,
          terraform fmt -check

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker:19.03.5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test
        run: |
          echo "Test and Lint"
          apk add python3-dev libffi-dev openssl-dev gcc libc-dev make
          pip3 install -I docker-compose==1.26.2
          docker-compose -f docker-compose.test.yml run api_test
