name: validate and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
#   validate_terraform:
#     runs-on: ubuntu-latest
#     container: hashicorp/terraform:0.12.21
#     steps:
#       - uses: actions/checkout@v2
#       - name: validate terraform
#         run: |
#           echo "Validate Terraform"
#           cd deploy/
#           terraform init -backend=false
#           terraform validate
#           terraform fmt -check

  test:
    runs-on: ubuntu-latest
    container: docker:19.03.5
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          echo "Test and Lint"
          apk add python3-dev musl-dev libffi-dev openssl-dev gcc cargo libc-dev make
          pip3 install -I docker-compose==1.26.2
          docker-compose -f docker-compose.test.yml run api_test
